languageCode = "en-us"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true
baseurl = "https://mobileroboticsskoltech.github.io/SmartPortraits/"
RelativeURLs=true
CanonifyURLs=true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

[[Params.listeLangues]]
code = "en"

[Languages]

[Languages.en]
weight = 2
languageCode = "en-us"
title = ""
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = ""
footerAboutTitle = ""

footerLocationDescription = ""
footerLocationTitle = ""


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "SmartPortraits"
description = "Depth Powered Handheld Smartphone Dataset of Human Portraits for State Estimation, Reconstruction and Synthesis"
button  = true
btnText = "Download"
btnURL  = "download"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Fill the gap in realistic human rendering and 3D reconstruction"
description = "Our dataset provides smartphone data (video and IMU) precisely synchronized with depth captured on Azure Kinect DK sensor as the source of ground truth information for 3D reconstruction, rendering, and single-shot depth estimation tasks. Recordings were performed with blinking flash for possible usage in re-lighting tasks. Within the dataset, we deliver high-quality trajectories of the smartphone and segmentation masks for human avatars."

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "Request data"
title   = "Contact Us"
subtitle= "Email to avatar.dataset@gmail.com to get data"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "hardware"
url     = "hardware"
weight  = 2
[[menu.nav]]
name    = "download"
url     = "download"
weight  = 3

